---
- name: Criar incidente no SNOW 
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    sn_short_description: "Automação Servicenow"
    sn_description: "Incidente criado via Ansible"
    sn_impact: low
    sn_urgency: low
  collections:
    - servicenow.itsm

  tasks:
    - name: Criar incidente no SNOW
      servicenow.itsm.incident:
        state: new
        instance:
          host: "{{ snow_instance }}"
          username: "{{ snow_username }}"
          password: "{{ snow_password }}"
        caller: "{{ lookup('env', 'SN_USERNAME') }}"
        short_description: "{{ sn_short_description }}"
        description: "{{ sn_description }}"
        impact: "{{ sn_impact }}"
        urgency: "{{ sn_urgency }}"
      register: new_incident

    - name: coletar informações do incidente
      set_fact:
        incident_number_cached: "{{ new_incident.record.number }}"
        cacheable: true

    - name: Mostrar informações do incidente
      debug:
        msg: "Um novo incidente foi criado {{ new_incident.record.number }}"

    - name: Set host IP address variable
      set_stats:
        data:
          incident_number: "{{ new_incident.record.number }}"